### ISSUE TITLE
[Bug] Latest release causing game crash when opening sound settings

### ISSUE THREAD

**Issue by ArtpokeBr** [TeamWizardry/Wizardry#356]
### Observed behaviour

When using the latest release version, one can edit the settings once and after that will have their game crash with a ArrayIndexOutOfBoundsException rolling back the version by one appears to resolve this issue, appears like a regression.

### Expected behaviour

Getting to the sound settings consistently

### Steps to reproduce

Delete options file
- Open game
- Edit the settings once
- Restart game
- Now should be no longer working and crash

### Crashlog
https://pste.ch/ucuzoziyec

Environment (Singleplayer/Server, etc.)
Issue present on both sides

### Mod version
4.3.12

### Minecraft version
1.12.2

### Forge version
14.23.5.2859

**Comment by Hadaward** [comment]
Thanks, this issue is fixed here https://github.com/Hadaward/Wizardry/releases/tag/v0.11.3 i'll ask @murapix to upload it to curseforge.

**Comment by ArtpokeBr** [comment]
well.... it seems that it still happens, same thing, just by opening the sound settings.
https://mclo.gs/E5XmQcR

although now I'am using forge 60 instead of 59 and of course on the latest mod version in 1.12

at least this time it doesn't blame wizardry directly tho ¯\_(ツ)_/¯

**Comment by Hadaward** [comment]
Yup, this time the incompatibility is with "Extra Sounds" mod, i'll check when available, thx

**Comment by ralseilii** [comment]
seems crash whenever you have new sound-related mod.Use Wizardry v0.11.1 can fix the crash.

**Comment by Deepfriedyag** [comment]
I have the same issue with the latest version of the wizardry mod on curseforge. Removing both Quark and options.txt somehow fixes the issue for me. Wanted to mention as it might help to find a fix. At the moment I have to remove wizardry from my modpack. It took ages just to even find what mod caused it. I accidentally stumbled upon this github issue.

[crash-2025-05-21_23.20.17-client.txt](https://github.com/user-attachments/files/20377179/crash-2025-05-21_23.20.17-client.txt)
