### ISSUE TITLE
Mana in basic halo vanishing after relog

### ISSUE THREAD

**Issue by MitchSaad** [TeamWizardry/Wizardry#84]
Logging out and back in seems to be making the mana from a basic halo vanish - tested twice, logging out for ~30sec, same result. syringes remain consumed, but 80% of mana has disappeared.

![full](https://user-images.githubusercontent.com/32118205/34438949-3dcccd74-ecf6-11e7-8e0a-fa7616cba96b.png)

![empty](https://user-images.githubusercontent.com/32118205/34438951-402ab64e-ecf6-11e7-8feb-da4178f4a54b.png)

**Comment by Demoniaque** [comment]
This is just bizarre... I'm able to reproduce it but what the crap...

**Comment by MitchSaad** [comment]
Story of my life

**Comment by Demoniaque** [comment]
I think this is fixed now. Check 0.7.

**Comment by YaibaToKen** [comment]
I would like to report this is still happening in 0.7.2, the latest version available on curse and twitch

**Comment by Demoniaque** [comment]
thanks for the feedback. will look into it.

**Comment by Demoniaque** [comment]
Does this still happen in 0.9.x?

**Comment by Demoniaque** [comment]
FINALLY FIXED.
